name: Build and Release

on:
  push:
    paths:
      - 'src/osu_to_sdx.py'
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r src/requirements.txt

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile --distpath dist src/osu_to_sdx.py

      - name: Generate Release Version
        id: version
        run: |
          set SHA_SHORT=%GITHUB_SHA:~0,7%
          set VERSION=1.0%GITHUB_RUN_NUMBER%-%SHA_SHORT%
          echo version=%VERSION%>>%GITHUB_OUTPUT%
          shell: cmd

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 1.0${{ github.run_number }}
          name: Release ${{ steps.version.outputs.version }}
          files: dist/osu_to_sdx.exe
